services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goal-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    env_file:
      - ./backend/.env
    depends_on:
      - database


  database:
    image: postgres:16
    container_name: goal-postgres
    environment:
      POSTGRES_DB: project_goal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BRIMAS0501
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: