import { lightColors, radius, shadows, spacing, typography, fontFamily } from './theme';

export const COLORS = {
  background: lightColors.background,
  surface: lightColors.card,
  surfaceWhite: lightColors.card,
  surfaceContainer: lightColors.surfaceMuted,
  surfaceContainerLow: '#F8FAFC',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerHigh: '#E2E8F0',
  surfaceContainerHighest: '#CBD5E1',
  surfaceAlt: '#F8FAFC',
  surfaceStrong: '#E2E8F0',
  primary: lightColors.primary,
  primaryLight: '#DCFCE7',
  primaryContainer: lightColors.primaryContainer,
  primaryFixed: lightColors.primary,
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#14532D',
  success: lightColors.success,
  successLight: '#DCFCE7',
  text: lightColors.text,
  textSecondary: lightColors.textSecondary,
  textTertiary: lightColors.textTertiary,
  onSurface: lightColors.text,
  onSurfaceVariant: lightColors.textSecondary,
  outline: lightColors.border,
  outlineVariant: '#CBD5E1',
  error: lightColors.danger,
  errorContainer: '#FEE2E2',
  errorLight: '#FEE2E2',
  onErrorContainer: '#7F1D1D',
  floodlight: lightColors.warning,
  inverseSurface: '#0F172A',
  inverseOnSurface: '#F8FAFC',
  divider: lightColors.border,
  shadow: 'rgba(15,23,42,0.08)',
  shadowDark: 'rgba(15,23,42,0.14)',
  warmWhite: '#FFFFFF',
  cardBg: '#FFFFFF',
  warningText: '#92400E',
  warningBg: '#FEF3C7',
  warningBorder: '#FDE68A',
  warningIcon: '#D97706',
  darkSurface: '#1E293B',
  darkSurfaceAlt: '#334155',
  darkScreen: '#0F172A',
  darkBorder: '#334155',
  darkText: '#F8FAFC',
  darkTextSecondary: '#CBD5E1',
  darkHandle: '#475569',
};

export const AUTH_COLORS = {
  primary: lightColors.primary,
  primaryDark: '#14532D',
  primaryContainer: '#DCFCE7',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#14532D',
  success: lightColors.success,
  successContainer: '#DCFCE7',
};

export const SIZES = {
  borderRadiusSm: radius.sm,
  borderRadius: radius.md,
  borderRadiusLg: radius.lg,
  borderRadiusXl: radius['2xl'],
  borderRadiusFull: radius.full,
  padding: spacing.gutter,
  paddingMobile: spacing.lg,
  gutter: spacing.lg,
  stackSm: spacing.sm,
  stackMd: spacing.lg,
  stackLg: spacing['3xl'],
  sectionGap: spacing.section,
};

export const SHADOWS = shadows;
export const FONT_FAMILY = fontFamily;

export const FONTS = {
  headlineLg: typography.headlineLg,
  headlineMd: typography.headlineMd,
  headlineSm: typography.headlineSm,
  titleLg: typography.titleLg,
  titleMd: typography.titleMd,
  titleSm: { ...typography.bodySm, fontWeight: '700' as const },
  bodyLg: typography.bodyLg,
  bodyMd: typography.bodyMd,
  bodySm: typography.bodySm,
  labelLg: typography.labelLg,
  labelMd: typography.labelMd,
  labelSm: typography.labelSm,
  buttonLg: typography.buttonLg,
  buttonMd: typography.buttonMd,
};
