export const COLORS = {
  background: '#F3F7F4',
  surface: '#FFFFFF',
  surfaceWhite: '#FFFFFF',
  surfaceContainer: '#EFF6EE',
  surfaceContainerLow: '#F3F7F4',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerHigh: '#E2E9E4',
  surfaceContainerHighest: '#DCE9E2',
  surfaceAlt: '#F8FAF6',
  surfaceStrong: '#DDE7DE',
  primary: '#1E8A4C',
  primaryLight: '#E6F4E8',
  primaryContainer: '#DCF2DD',
  primaryFixed: '#1E8A4C',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#0F3D22',
  success: '#1E8A4C',
  successLight: '#E6F4E8',
  text: '#16201A',
  textSecondary: '#5B6960',
  textTertiary: '#889189',
  onSurface: '#16201A',
  onSurfaceVariant: '#5B6960',
  outline: '#E2E9E4',
  outlineVariant: '#DDE5E0',
  error: '#E0533D',
  errorContainer: '#FEEBE9',
  errorLight: '#FFE6E1',
  onErrorContainer: '#410002',
  floodlight: '#FFC93C',
  inverseSurface: '#2C322F',
  inverseOnSurface: '#F3F7F4',
  divider: '#E2E9E4',
  shadow: 'rgba(0,0,0,0.06)',
  shadowDark: 'rgba(0,0,0,0.10)',
  warmWhite: '#FFFFFF',
  cardBg: '#FFFFFF',
  accentPurple: '#8B5CF6',
  accentPurpleLight: '#F1EAFB',
  accentOrange: '#E97A1F',
  accentOrangeLight: '#FFF3E6',
};

export const AUTH_COLORS = {
  primary: '#1E8A4C',
  primaryDark: '#0F3D22',
  primaryContainer: '#DCF2DD',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#0F3D22',
  success: '#1E8A4C',
  successContainer: '#DCF2DD',
};

export const SIZES = {
  borderRadiusSm: 8,
  borderRadius: 12,
  borderRadiusLg: 16,
  borderRadiusXl: 24,
  borderRadiusFull: 999,
  padding: 20,
  paddingMobile: 16,
  gutter: 16,
  stackSm: 8,
  stackMd: 16,
  stackLg: 32,
  sectionGap: 24,
};

export const SHADOWS = {
  xs: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
    boxShadow: '0px 1px 2px rgba(0,0,0,0.04)',
  },
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    boxShadow: '0px 1px 3px rgba(0,0,0,0.05)',
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 4,
    boxShadow: '0px 2px 8px rgba(0,0,0,0.07)',
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.09,
    shadowRadius: 14,
    elevation: 6,
    boxShadow: '0px 4px 14px rgba(0,0,0,0.09)',
  },
  xl: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.11,
    shadowRadius: 24,
    elevation: 8,
    boxShadow: '0px 8px 24px rgba(0,0,0,0.11)',
  },
  primary: {
    shadowColor: '#007a4f',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    boxShadow: '0px 3px 8px rgba(0,122,79,0.20)',
  },
  authPrimary: {
    shadowColor: '#1a56db',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    boxShadow: '0px 3px 8px rgba(26,86,219,0.20)',
  },
};

export const FONTS = {
  headlineLg: { fontFamily: 'Montserrat', fontSize: 28, fontWeight: '700' as const, lineHeight: 34 },
  headlineMd: { fontFamily: 'Montserrat', fontSize: 20, fontWeight: '700' as const, lineHeight: 26 },
  headlineSm: { fontFamily: 'Montserrat', fontSize: 16, fontWeight: '700' as const, lineHeight: 22 },
  titleLg: { fontFamily: 'Montserrat', fontSize: 16, fontWeight: '600' as const, lineHeight: 22 },
  titleMd: { fontFamily: 'Montserrat', fontSize: 14, fontWeight: '600' as const, lineHeight: 20 },
  titleSm: { fontFamily: 'Montserrat', fontSize: 13, fontWeight: '600' as const, lineHeight: 18 },
  bodyLg: { fontFamily: 'Montserrat', fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
  bodyMd: { fontFamily: 'Montserrat', fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
  bodySm: { fontFamily: 'Montserrat', fontSize: 12, fontWeight: '400' as const, lineHeight: 16 },
  labelLg: { fontFamily: 'Montserrat', fontSize: 14, fontWeight: '600' as const, lineHeight: 18 },
  labelMd: { fontFamily: 'Montserrat', fontSize: 12, fontWeight: '600' as const, lineHeight: 16 },
  labelSm: { fontFamily: 'Montserrat', fontSize: 10, fontWeight: '700' as const, lineHeight: 14 },
  buttonLg: { fontFamily: 'Montserrat', fontSize: 16, fontWeight: '700' as const, lineHeight: 20 },
  buttonMd: { fontFamily: 'Montserrat', fontSize: 14, fontWeight: '600' as const, lineHeight: 18 },
};
